In [1]:
import numpy as np

In [ ]:
# Basic functions

In [3]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Square roots
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
# Exponenital
np.exp(array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
# Binary functions

# function a and b are random nmbers in a normal distribution
A = np.random.randn(10)
B = np.random.randn(10)

In [11]:
A, B

(array([ 1.50153904,  0.81280629, -1.26388713,  0.56353107,  1.64566491,
         0.46016237,  0.82095215, -0.95320355,  0.37115189, -1.13349248]),
 array([-1.56774754, -2.01606149, -0.01531508,  0.97769635,  1.76489274,
        -0.88434572, -0.32260257,  0.37995371, -1.07871424,  1.40217707]))

In [10]:
# Adding both vectors
A + B

array([-0.0662085 , -1.20325519, -1.27920221,  1.54122742,  3.41055765,
       -0.42418335,  0.49834958, -0.57324984, -0.70756235,  0.26868458])

In [12]:
# Finding the max of the arrays
np.maximum(A, B)

array([ 1.50153904,  0.81280629, -0.01531508,  0.97769635,  1.76489274,
        0.46016237,  0.82095215,  0.37995371,  0.37115189,  1.40217707])

In [13]:
# For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True