In [43]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.externals import joblib 


In [3]:
from sklearn.ensemble import RandomForestRegressor

In [4]:
# tools that'll help us from cv
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [5]:
# importing some metrics we can use to evaluate our model performance
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
# Load wine data from remote URLPython
dataset_url = 'http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
data = pd.read_csv(dataset_url)

In [8]:
data.head() # Notice how the data is seperated with the ';'. We need to use that as separtors

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0   7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1   7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2  7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3  11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4   7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5

In [9]:
data = pd.read_csv(dataset_url, sep=';') # Using the sep parameters

In [10]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [11]:
data.shape # There are 1599 observations with 12 features

(1599, 12)

In [12]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

We have the following
- quality (target)
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol features


In [18]:
## Splitting the data into training and testing set ##

In [13]:

# Splitting the data into training and test sets at the beginning 
# of your modeling workflow is crucia l for getting a realistic
# estimate of your model's performance.
#

y_var = data.quality
X_fts = data.drop('quality', axis=1)

In [17]:
# Using the train_test_split function to create mult. testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X_fts, y_var, 
                                                    test_size=0.2, 
                                                    random_state=123, 
                                                    stratify=y_var)

# Info. on parameters
# test_size: The pct of the test_size, thus 20% will be test, 80% will be training
# random_state: We set up an arbitrary number so we can reproduce the results (we do with the seed)
# stratify: You are basically asking the model to take the training and test set 
#           such that the class proportion is same as of the whole dataset, which is the right thing to do.

In [ ]:
## Standarizing our features ##

In [28]:
# Prepocessing 
# Here's what that process looks like:
#    - Fit the transformer on the training set (saving the means and standard deviations)
#    - Apply the transformer to the training set (scaling the training data)
#    - Apply the transformer to the test set (using the same means and standard deviations)

scaler = preprocessing.StandardScaler().fit(X_train) # This saves the scaler object with the appr. mean and std dev


array([  1.16664562e-16,  -3.05550043e-17,  -8.47206937e-17,
        -2.22218213e-17,   2.22218213e-17,  -6.38877362e-17,
        -4.16659149e-18,  -2.54439854e-15,  -8.70817622e-16,
        -4.08325966e-16,  -1.17220107e-15])

In [29]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
# Performing the normalization with the info. from the training set
# to the testing set
X_train_scaled.mean(axis=0) # This should be 0?

array([  1.16664562e-16,  -3.05550043e-17,  -8.47206937e-17,
        -2.22218213e-17,   2.22218213e-17,  -6.38877362e-17,
        -4.16659149e-18,  -2.54439854e-15,  -8.70817622e-16,
        -4.08325966e-16,  -1.17220107e-15])

In [31]:
X_test_scaled = scaler.transform(X_test)

In [32]:
X_test_scaled.mean(axis=0), X_test_scaled.std(axis=0) 
# Notice how the scaled features in the test set are not perfectly centered at zero 
# with unit variance! This is exactly what we'd expect, as we're transforming  
# the test set using the means from the training set, not from the test set itself.

(array([ 0.02776704,  0.02592492, -0.03078587, -0.03137977, -0.00471876,
        -0.04413827, -0.02414174, -0.00293273, -0.00467444, -0.10894663,
         0.01043391]),
 array([ 1.02160495,  1.00135689,  0.97456598,  0.91099054,  0.86716698,
         0.94193125,  1.03673213,  1.03145119,  0.95734849,  0.83829505,
         1.0286218 ]))

In [33]:
# Creating a pipeline
pipeline = make_pipeline(preprocessing.StandardScaler(), 
                         RandomForestRegressor(n_estimators=100))

In [ ]:
## Declare hyperparameters to tune ##

In [34]:
pipeline.get_params() # The different hyperparams. that can be motified

{'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
            max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
 'randomforestregressor__bootstrap': True,
 'randomforestregressor__criterion': 'mse',
 'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'auto',
 'randomforestregressor__max_leaf_nodes': None,
 'randomforestregressor__min_impurity_split': 1e-07,
 'randomforestregressor__min_samples_leaf': 1,
 'randomforestregressor__min_samples_split': 2,
 'randomforestregressor__min_weight_fraction_leaf': 0.0,
 'randomforestregressor__n_estimators': 100,
 'randomforestregressor__n_jobs': 1,
 'randomforestregressor__oob_score': False,
 'randomforestregressor__random_state': None,
 'rando

In [36]:
# Using only your training set, you can use CV to evaluate 
# different hyperparameters and estimate their effectiveness.
# This allows you to keep your test set "untainted" and save 
# it for a true hold-out evaluation when you're finally ready to select a model.

# The best practice when performing CV is to include your data preprocessing 
# steps inside the cross-validation loop

hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

clf = GridSearchCV(pipeline, hyperparameters, cv=10)
 
# Fit and tune model
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False))]),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [37]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'sqrt'}

In [38]:
clf.refit # get a small performance improvement by refitting the model on the entire training set.

True

In [39]:
y_pred = clf.predict(X_test)

In [40]:
r2_score(y_test, y_pred)

0.46918288031963207

In [41]:
mean_squared_error(y_test, y_pred)

0.34252218750000002

In [44]:
joblib.dump(clf, 'rf_regressor.pkl')

['rf_regressor.pkl']