In [1]:
import numpy as np
import pandas as pd

from pandas import DataFrame, Series

In [2]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Axis 1 means we are doing throgh the row
np.concatenate([array1,array1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
# Axis 1 means we are doing throgh the column
np.concatenate([array1,array1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['a','b','c'])
ser1

a    0
b    1
c    2
dtype: int64

In [8]:
ser2 = Series([3,4], index=['d','e'])
ser2

d    3
e    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
a  0.0  NaN
b  1.0  NaN
c  2.0  NaN
d  NaN  3.0
e  NaN  4.0

In [12]:
pd.concat([ser1,ser2],axis=0)

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [13]:
# Good way to remember which series is which
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  a    0
      b    1
      c    2
cat2  d    3
      e    4
dtype: int64

In [17]:
# randn here means 4 rows of the 3 columns of random numbers
dframe1 = DataFrame(np.random.randn(4,3), columns=['x','y','z'])
dframe1

x         y         z
0  0.138805 -0.460465 -1.538434
1 -0.382493  1.544135 -0.208631
2  0.115261  0.303316 -0.276999
3  1.207231  0.595291  1.011618

In [19]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['a','x','c'])
dframe2

a         x         c
0  0.401061 -0.366761  1.046606
1 -0.430136  0.206938  0.142252
2 -1.135838  0.240913 -0.808498

In [22]:
# Uses the columns as the key
pd.concat([dframe1, dframe2], axis=0)

a         c         x         y         z
0       NaN       NaN  0.138805 -0.460465 -1.538434
1       NaN       NaN -0.382493  1.544135 -0.208631
2       NaN       NaN  0.115261  0.303316 -0.276999
3       NaN       NaN  1.207231  0.595291  1.011618
0  0.401061  1.046606 -0.366761       NaN       NaN
1 -0.430136  0.142252  0.206938       NaN       NaN
2 -1.135838 -0.808498  0.240913       NaN       NaN

In [23]:
# Uses the columns as the key
pd.concat([dframe1, dframe2], axis=1)

x         y         z         a         x         c
0  0.138805 -0.460465 -1.538434  0.401061 -0.366761  1.046606
1 -0.382493  1.544135 -0.208631 -0.430136  0.206938  0.142252
2  0.115261  0.303316 -0.276999 -1.135838  0.240913 -0.808498
3  1.207231  0.595291  1.011618       NaN       NaN       NaN

In [24]:
# Uses the columns as the key, ignore index (noticed how the index in axis=0 is not continues)
pd.concat([dframe1, dframe2], axis=0, ignore_index=True)

a         c         x         y         z
0       NaN       NaN  0.138805 -0.460465 -1.538434
1       NaN       NaN -0.382493  1.544135 -0.208631
2       NaN       NaN  0.115261  0.303316 -0.276999
3       NaN       NaN  1.207231  0.595291  1.011618
4  0.401061  1.046606 -0.366761       NaN       NaN
5 -0.430136  0.142252  0.206938       NaN       NaN
6 -1.135838 -0.808498  0.240913       NaN       NaN

In [25]:
# For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'