In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
df = DataFrame(np.arange(20).reshape(5,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [5]:
# array with permutation or a random order
blender = np.random.permutation(4)

blender

array([3, 0, 2, 1])

In [6]:
# changing the order of the index
# according to the blender index
df.take(blender)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7

In [8]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])
box

array([1, 2, 3])

In [10]:
# WITH REPLACEMENT
shaker = np.random.randint(0, len(box), size=10)
shaker

array([1, 1, 1, 0, 2, 2, 1, 2, 2, 0])

In [12]:
#Now lets grab form the box
hand_grabs = box.take(shaker)
hand_grabs

array([2, 2, 2, 1, 3, 3, 2, 3, 3, 1])